controller_manager:
  ros__parameters:
    update_rate: 100
    
    neck_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

neck_joint_trajectory_controller:
  ros__parameters:
    joints:
      - neck_yaw_joint
      - neck_pitch_joint
      - neck_roll_joint
    
    command_interfaces:
      - position
    
    state_interfaces:
      - position
      - velocity
    
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
